spring:
  datasource:
    url: jdbc:mysql://192.168.88.166:3301/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: zhouzhou123

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhouzhou.pagehelper.dao.entity
