spring:
  datasource:
    url: jdbc:mysql://20.21.1.147:3301/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhouzhou.pagehelper.dao.entity
